### ISSUE TITLE
Not really an issue but...

### ISSUE THREAD

**Issue by Chilly0046** [rodyager/RWTS-PDFwriter#1]
Only prints at 300dpi, really would be great to have 600dpi, as everything else is spot on :)

**Comment by shamims** [comment]
Echo this request! Ability to choose DPI would be a huge win. :)

**Comment by rodyager** [comment]
Well, actually, it does NO downsampling. It creates a pdf file in which any bitmap images are at the resolution that the application sent to the OS for "printing". For example, this 1200 dpi checkerboard png is "printed" at 1200 dpi by PDFwriter when printed from preview.
If it were 300 dpi, the pdf would be a uniform grey under high magnification.
![checker](https://cloud.githubusercontent.com/assets/1384461/17005824/ca902f1a-4f1f-11e6-9aaa-fe7c202cb3a7.png)

**Comment by shamims** [comment]
Thanks for the explanation. The issue I'm trying to solve is printing from
a flash application (via any browser) that is sending vector art to the
printer. When printing to a physical printer, the DPI chosen from the print
dialog menu has a direct bearing on the quality of the print job. For
instance a 300 DPI print job tesselates edges for very small text. But
choosing to print 1200 DPI will drastically improve edge fidelity of
smaller text.

However when printing to PDF, it seems that the Save to PDF feature in OSX
caps output to 300 DPI. I was looking for a print-to-pdf solution that
could control the DPI output and thereby solve my problem.

--
*Shamim Sahba*
OfficeSpace Software

t: +1 646 249 6110
shamim@officespacesoftware.com
www.officespacesoftware.com

**Comment by Chilly0046** [comment]
I see an all grey Image?

Mike

**Comment by rodyager** [comment]
You need to zoom in an awful lot to see the detail. The image is a checkerboard pattern of 1 pixel by 1 pixel black and white squares at 1200 dpi.

That’s the point. At 300 dpi or even 600 dpi, it is uniformly grey. Only at 1200 dpi can you see that there is alternating black and white detail.

Rod


On 21 Jul. 2016, at 9:06 am, Chilly0046 <notifications@github.com<mailto:notifications@github.com>> wrote:

I see an all grey Image?

Mike

**Comment by Chilly0046** [comment]
OK, I just tried a print at 600 dpi to the PDF writer, and a 300dpi the
same and compared.

The 600 is much better, so thanks, it DOES do what I wanted it to,

Many thanks for your replys.

Best regards,
Mike
