### ISSUE TITLE
Very big file size

### ISSUE THREAD

**Issue by aburkov** [rodyager/RWTS-PDFwriter#11]
Hi,

When I print a 300-page book, the output file size is 2GB. Is there a way to reduce the size of the file?

Thanks!

**Comment by aminmkhan** [comment]
I printed a two page PDF (originally 900 KB) but that printed to 43 MB, so there must be some configuration to reduce the print size.

**Comment by lanec** [comment]
When I have large print jobs that I need to reduce in file size I use Adobe Acrobat CC (Paid Edition) to save with reduced file size. I don't know if paid is an option for you but it works perfectly.
