### ISSUE TITLE
compatibilità

### ISSUE THREAD

**Issue by Liuzzino** [rodyager/RWTS-PDFwriter#12]
RWTS-PDFwriter è compatibile col nuovo sistema operativo macOS Big Sur???

**Comment by rodyager** [comment]
Yes.

Sent from my iPhone

On 23 Dec 2020, at 9:25 pm, Liuzzino <notifications@github.com> wrote:

﻿

RWTS-PDFwriter è compatibile col nuovo sistema operativo macOS Big Sur???
