### ISSUE TITLE
Change the output folder

### ISSUE THREAD

**Issue by Quameda** [rodyager/RWTS-PDFwriter#13]
Changing the output folder would be great.

**Comment by twizzay-code** [comment]
Hey @Quameda,

I forked this and made a quick modification, instructing how to do what you are describing.

You will need to build the package from source in order for this to work.

https://github.com/twizzay-code/RWTS-PDFwriter

**Comment by macmachado** [comment]
This is better comented on https://github.com/rodyager/RWTS-PDFwriter/pull/15
before that, was comented on https://github.com/rodyager/RWTS-PDFwriter/issues/14

**Comment by rodyager** [comment]
While this enables anyone who builds the project themselves to make it work for them, it doesn’t help the average user who just wants something they can install.

However, this is something I do want to fix. My current intention is to provide a “Helper” app that allows the user to choose the folder in which the print jobs will appear.

Just need to find the couple of hours to implement it.

Rod

On 24 Mar 2022, at 5:00 am, Twizzay ***@***.******@***.***>> wrote:



Hey @Quameda<https://github.com/Quameda>,

I forked this and made a quick modification, instructing how to do what you are describing.

You will need to build the package from source in order for this to work.

https://github.com/twizzay-code/RWTS-PDFwriter
