### ISSUE TITLE
Job not appearing in Users/Shared/PDFwriter

### ISSUE THREAD

**Issue by HeyJwd** [rodyager/RWTS-PDFwriter#17]
Print leaves the spool as as a complete job but fails to appear in the write folder.
Has worked flawlessly up until job_1263.

**Comment by rodyager** [comment]
Have you recently updated your OS.  If so, the most likely fix is to run the installer again.

Rod

On 11 Dec 2021, at 5:38 am, HeyJwd ***@***.******@***.***>> wrote:



Print leaves the spool as as a complete job but fails to appear in the write folder.
Has worked flawlessly up until job_1263.
