### ISSUE TITLE
Needs revision to work with OS 12 (Monterey) and M1 Macs

### ISSUE THREAD

**Issue by JPDemers1** [rodyager/RWTS-PDFwriter#18]
Installation fails on an M1 Mac running Monterey OS.

**Comment by rodyager** [comment]
Can you please run the istaller again.

When the installation fails, go to the Installer’s Window menu and choose Installer Log (or Command-L)

On the right hand side, choose “Show Errors and Progress”

Then copy everything in the window and send it to me so that I can have some idea as to what failed.

Rod



On 27 Apr 2022, at 2:46 am, JPDemers1 ***@***.******@***.***>> wrote:



Installation fails on an M1 Mac running Monterey OS.

**Comment by GeorgiyDemo** [comment]
> Installation fails on an M1 Mac running Monterey OS.

Just tried to install the latest version v1.0.1 on my M1 Macbook Air with macOS Monterey 12.3 (21E230).
Everything works well.

If you have any logs, please share it

**Comment by rodyager** [comment]
Version 2 has Universal binaries (among other improvements)

**Comment by AdamBrousseau** [comment]
@rodyager I tried v2 on a mac m1 and it said it required Rosetta. Is this expected? I was assuming that the universal binary wouldn't need it.

**Comment by rodyager** [comment]
I expected that it would work. I don’t have an M1 machine, so I have no way to test.

Rod

Sent from my iPhone

On 16 Nov 2022, at 8:53 pm, AdamBrousseau ***@***.***> wrote:

﻿

@rodyager<https://github.com/rodyager> I tried v2 on a mac m1 and it said it required Rosetta. Is this expected? I was assuming that the universal binary wouldn't need it.

**Comment by kbernhagen** [comment]
You might qualify for an open-source account at MacStadium.

**[https://www.macstadium.com/opensource](url)**

**Comment by JPDemers1** [comment]
Installed the latest revision (Version 2.0) on my M1 Mini (OS 12 Monterey) and it works perfectly.

**Comment by JPDemers1** [comment]
On my M1 Mini, Rosetta appears to be installed.  At least, the components are present:
/Library/Apple/usr/lib/libRosettaAot.dylib
/Library/Apple/usr/libexec/oah/libRosettaRuntime
/Library/Apple/usr/share/rosetta/rosetta

(That last item is a curious bit of Haiku, at least when opened with TextEdit!)

Note that the installer notice re needing Rosetta might be bogus: 
https://github.com/fish-shell/fish-shell/issues/8566

**Comment by rodyager** [comment]
Thanks for the clue. 
Once I knew it was the Installer that was asking for Rosetta, it became obvious that I needed to look at my installer packaging, and it was easy to discover that I had omitted to list arm64 as a supported architecture. 

A new installer will appear shortly

Rod

**Comment by AdamBrousseau** [comment]
The new pkg is still saying it requires Rosetta unfortunately.

**Comment by rodyager** [comment]
I’m not confident that I built the new package correctly. I’ve replaced it wth a properly constructed package.

Could you please check if this one will install without requiring Rosetta and let me know.

Sorry to be a pain.

Rod

On 21 Nov 2022, at 5:51 pm, AdamBrousseau ***@***.***> wrote:



The new pkg is still saying it requires Rosetta unfortunately.

**Comment by sxa** [comment]
Looks ok to me now but I'll let Adam confirm that it's good on his system too - thanks @rodyager!

**Comment by AdamBrousseau** [comment]
I tried a different machine and it worked fine. Must be something wrong with the first machine I was trying.
Thanks for updating the package @rodyager. Much appreciated!
