### ISSUE TITLE
Remove prefix “job_***” from filenames?

### ISSUE THREAD

**Issue by alexfazio** [rodyager/RWTS-PDFwriter#19]
First of all, let me thank you for this fantastic utility. As you can see [here](https://discourse.devontechnologies.com/t/devonthink-as-standard-printer/70103/8) it's extremely useful for DEVONthink users.

I didn't find anything about this in your resources, so I assume this is a feature request rather than a question...

Is there any possibility to set up [RWTS-PDFwriter from Rod Yager](https://github.com/rodyager/RWTS-PDFwriter) to not add the prefix “job” to each new file?

![image](https://user-images.githubusercontent.com/34505954/170997260-9505e589-a603-4a6e-ab49-3a703e503e22.png)

**Comment by ericcobia** [comment]
I also find this tool very helpful and have a like request. The job and the integer would be great to be removed or at least moved to after the title. I have tried adjusting the source but nothing works

**Comment by rodyager** [comment]
Unfortunately, the file name is completely under the control of the OS print system.

The printer driver can’t change it.

Rod

Sent from my iPhone

On 17 Jun 2022, at 5:15 am, ericcobia ***@***.***> wrote:

﻿

I also find this tool very helpful and have a like request. The job and the integer would be great to be removed or at least moved to after the title. I have tried adjusting the source but nothing works

**Comment by ericcobia** [comment]
to help with the alexfazio, in this file in the source code.
/RWTS-PDFwriter-master/sources/pdfwriter.m
line451 
you can do this:
        //snprintf(title, BUFSIZE, "job_%i %s", job, cmdtitle);
        snprintf(title, BUFSIZE, "%i %s", job, cmdtitle);

the "job_" disappears, but the %i cannot be removed without an complie error so your output  file starts with a number now

change that and run the build script.sh and you have half the change done :)

**Comment by ericcobia** [comment]
the %i  number does seem to be out of control of script as rodyager states. im still wasting time trying tho

**Comment by rodyager** [comment]
Ok.

Using

snprintf(title, BUFSIZE, “%s”, cmdtitle);

as the replacement line 451 should do the trick.

Rod


Sent from my iPhone

On 18 Jun 2022, at 2:53 am, ericcobia ***@***.***> wrote:

﻿

to help with the alexfazio, in this file in the source code.
/RWTS-PDFwriter-master/sources/pdfwriter.m
line451
you can do this:
//snprintf(title, BUFSIZE, "job_%i %s", job, cmdtitle);
snprintf(title, BUFSIZE, "%i %s", job, cmdtitle);

the "job_" disappears, but the %i cannot be removed without an complie error so your output file starts with a number now

change that and run the build script.sh and you have half the change done :)

**Comment by ericcobia** [comment]
i confirm it works  - ty Rodyager!!!!!!

**Comment by rodyager** [comment]
The one caution. It will overwrite a previously “printed” document with the same name.

Rod

On 18 Jun 2022, at 7:53 am, ericcobia ***@***.******@***.***>> wrote:



i confirm it works - ty Rodyager!!!!!!
