### ISSUE TITLE
Excuse me but I am just curious, what does the 'RWTS' mean?

### ISSUE THREAD

**Issue by liuxhit** [rodyager/RWTS-PDFwriter#22]
As stated in the title... I tried GOOGLE but found nothing. Thank you very much for all the people who know it, and sorry to disturb you!

**Comment by rodyager** [comment]
Real World Technology Solutions -  the business that sponsors this work.

Rod

Sent from my iPhone

On 1 Jul 2022, at 1:45 am, liuxhit ***@***.***> wrote:

﻿

As stated in the title... I tried GOOGLE but found nothing. Thank you very much for all the people who know it, and sorry to disturb you!
