### ISSUE TITLE
Xcode build products in literal `~/tmp/xcode/Release`

### ISSUE THREAD

**Issue by kbernhagen** [rodyager/RWTS-PDFwriter#28]
Xcode builds are under project root in `~/tmp/xcode/Release`.

So, `buildscript.sh` does not find anything in `build/Release`.

This would be the build locations in the Xcode project.

**Comment by rodyager** [comment]
Build Locations
Build products path

This is the summary from XCode's Quick Help. 

The path at which all products will be placed when performing a build. Typically this path is not set per target, but is set per-project or per-user. By default, this is set to $(PROJECT_DIR)/build.

**Comment by kbernhagen** [comment]
Somehow it is not.
Open in Xcode, select project,bui;d settings, all, scroll down.

**Comment by rodyager** [comment]
<img width="1044" alt="Screenshot 2023-01-16 at 9 59 16 pm" src="https://user-images.githubusercontent.com/1384461/212662830-53fe8119-f298-4103-b59b-b6ec681c7f18.png">


Not sure why its different for you.

**Comment by kbernhagen** [comment]
Interesting.
I'll have to hunt down my problems later.
Thanks.
You can close this ticket.
