### ISSUE TITLE
This was the only way I could convert Adobe's PDF forms to a plain PDF

### ISSUE THREAD

**Issue by hikari-no-yume** [rodyager/RWTS-PDFwriter#3]
Adobe have a proprietary “PDF” form format that only Acrobat can create or open. Unfortunately, many things require real PDFs. The free version of Acrobat for macOS can open such forms, but refuses to convert them to plain PDFs. Of course, the first thing I tried was to try to use macOS's built-in PDF creation when “printing” from that free version of Acrobat, but Adobe specifically go out of their way to block that feature! So I ended up needing a print-to-PDF tool that Adobe hadn't specifically blocked, and yours was the first I found that worked for me and tricked Acrobat into doing what I so desperately needed of it. Thank you very much!

Apparently I am not the first macOS user to have had this problem with Adobe's evil proprietary format shenanigans, so it might even be worth mentioning as a reason to use this tool in the README, if you want.

Anyway, I know this isn't an “issue”, I just wanted to say thanks.

**Comment by rodyager** [comment]
Thanks, Andrea. 

Of course, that’s the principal use for this - but sometimes it is wiser to be discrete. 

Rod
