### ISSUE TITLE
Erroneous “Install Failed”

### ISSUE THREAD

**Issue by schmidhauser** [rodyager/RWTS-PDFwriter#31]
As you may see below, my install of v2.0.5 ended with the note that the install failed. The note is false, however: everything works perfectly fine.

M1, on macOS Ventura 13.1. – Thank you very much for the utility.

```
Jan 17 08:49:13 ION installd[649]: PackageKit: ----- Begin install -----
Jan 17 08:49:14 ION installd[649]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “RWTS-PDFwriter.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/aus/Downloads/RWTS-PDFwriter.pkg#pdfwriter.pkg, PKInstallPackageIdentifier=au.rwts.pdfwriter, NSLocalizedDescription=An error occurred while running scripts from the package “RWTS-PDFwriter.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cRWTS-PDFwriter.pkg\U201d.";
	    NSURL = "file:///Users/aus/Downloads/RWTS-PDFwriter.pkg#pdfwriter.pkg";
	    PKInstallPackageIdentifier = "au.rwts.pdfwriter";
	}
Jan 17 08:49:15 ION Installer[39675]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jan 17 08:49:15 ION Installer[39675]: Displaying 'Install Failed' UI.
Jan 17 08:49:15 ION Installer[39675]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

**Comment by rodyager** [comment]
Thanks. I’ve been able to reproduce this and it will be fixed shortly.

As you noted, the error occurs at a point where the software has been successfully installed. You will want to open the Utility to create the folder into which the printed files are placed.

The Utility can be found in /Library/Printers/RWTS/Utilities/   or you can go to System Preferences, open Printers & Scanners, choose the PDFWriter printer >  Options and Supplies > Utility and click on Open Printer Utility.

Alternatively, simply  reinstall. The Installer will correctly open the Utility the second time around.

Rod


On 18 Jan 2023, at 8:45 pm, Andreas ***@***.***> wrote:



As you may see below, my install of v2.0.5 ended with the note that the install failed. The note is false, however: everything works perfectly fine.

M1, on macOS Ventura 13.1. – Thank you very much for the utility.

Jan 17 08:49:13 ION installd[649]: PackageKit: ----- Begin install -----
Jan 17 08:49:14 ION installd[649]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “RWTS-PDFwriter.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/aus/Downloads/RWTS-PDFwriter.pkg#pdfwriter.pkg, PKInstallPackageIdentifier=au.rwts.pdfwriter, NSLocalizedDescription=An error occurred while running scripts from the package “RWTS-PDFwriter.pkg”.} {
            NSFilePath = "./postinstall";
            NSLocalizedDescription = "An error occurred while running scripts from the package \U201cRWTS-PDFwriter.pkg\U201d.";
            NSURL = "file:///Users/aus/Downloads/RWTS-PDFwriter.pkg#pdfwriter.pkg";
            PKInstallPackageIdentifier = "au.rwts.pdfwriter";
        }
Jan 17 08:49:15 ION Installer[39675]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jan 17 08:49:15 ION Installer[39675]: Displaying 'Install Failed' UI.
Jan 17 08:49:15 ION Installer[39675]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
