### ISSUE TITLE
update instructions

### ISSUE THREAD

**Issue by lanec** [rodyager/RWTS-PDFwriter#32]
Thanks for pushing out a new build. What is the recommendation for installation? Is it safe to install the latest version without uninstalling? Should we uninstall first?

**Comment by rodyager** [comment]
It is completely safe to install over the top of any previous version.

The installer takes care of any necessary cleaning up of earlier versions.

Rod

On 21 Jan 2023, at 3:38 pm, Lane Campbell ***@***.***> wrote:



Thanks for pushing out a new build. What is the recommendation for installation? Is it safe to install the latest version without uninstalling? Should we uninstall first?
