### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by bhatiasiddharth** [rodyager/RWTS-PDFwriter#34]
[Installer Log 1-Apr-2023.txt](https://github.com/rodyager/RWTS-PDFwriter/files/11129851/Installer.Log.1-Apr-2023.txt)

Getting the error "The Installer encountered an error that caused the installation to fail." I am using Mac OS 13.2.1
Uploading the log file.

**Comment by rodyager** [comment]
The log file is complaining about an error extracting the contents of the archive, so it seems that there has been some corruption in the package you downloaded.

Try downloading it afresh.

Rod

Sent from my iPhone

On 2 Apr 2023, at 2:04 am, Siddharth Bhatia ***@***.***> wrote:

﻿

Installer Log 1-Apr-2023.txt<https://github.com/rodyager/RWTS-PDFwriter/files/11129851/Installer.Log.1-Apr-2023.txt>

Getting the error "The Installer encountered an error that caused the installation to fail." I am using Mac OS 13.2.1
Uploading the log file.

**Comment by bhatiasiddharth** [comment]
Thanks for the prompt response. I tried multiple times, with another version as well, but the same error.

**Comment by rodyager** [comment]
I'm sorry to hear that you are having this problem. I've just downloaded the latest version on GitHub and installed it on my own machine without any issues. I'll keep an eye out for similar reports, but at the moment, there isn't enough to provide me with sufficient clues to be able to investigate effectively.

**Comment by bhatiasiddharth** [comment]
Thank you @rodyager for trying.
https://discussions.apple.com/thread/254600885 worked for me. Strange solution :)

**Comment by rodyager** [comment]
It’s a file and folder access issue. Installer doesn’t have permission to access your downloads folder.

To fix this (so it doesn’t happen when you want to install something else), go to System Settings > Privacy and Security > Files and Folders. Find Installer in the list of applications and open the disclosure. Toggle Downloads folder to “on”.

You probably answered “no” without thinking when you were initially asked (ages ago).

Rod

Sent from my iPhone

On 5 Apr 2023, at 10:53 am, Siddharth Bhatia ***@***.***> wrote:

﻿

Thank you @rodyager<https://github.com/rodyager> for trying.
https://discussions.apple.com/thread/254600885 worked for me. Strange solution :)

**Comment by bhatiasiddharth** [comment]
I think this is an issue with the latest OS update of Mac. Thanks for pointing it out.
