### ISSUE TITLE
Option to keep "job_####" prefix?

### ISSUE THREAD

**Issue by j-a-duke** [rodyager/RWTS-PDFwriter#36]
I'm sure I'm one of the few who want to keep the job prefix, but that let's me consecutively print multiple versions of a document, keeping the same name, which I can then send to someone for review/approval.

Would it be possible to add the ability to enable/disable this in the utility app?

Thanks.

Cheers,
Jon

**Comment by rodyager** [comment]
It’s moved from a prefix to a suffix. It now does the usual Apple thing of adding a number at the end.

Eg. Doc.pdf,  Doc 1.pdf, Doc 2.pdf etc.

I think this satisfies your requirement.

Rod

Sent from my iPhone

On 1 Jul 2023, at 3:25 am, j-a-duke ***@***.***> wrote:

﻿

I'm sure I'm one of the few who want to keep the job prefix, but that let's me consecutively print multiple versions of a document, keeping the same name, which I can then send to someone for review/approval.

Would it be possible to add the ability to enable/disable this in the utility app?

Thanks.

Cheers,
Jon
