### ISSUE TITLE
How to set custom size paper in macos. there is only default size displayed

### ISSUE THREAD

**Issue by skywalker123p** [rodyager/RWTS-PDFwriter#38]
How to set custom size paper in macos. there is only default size displayed. Thanks for help.

**Comment by rodyager** [comment]
PDFwriter has an extraordinarily long list of pre-set paper sizes for you to choose from by clicking on the pull-down list in the Paper Size section of the print menu.
<img width="600" alt="Screenshot 2023-08-22 at 7 07 33 am" src="https://github.com/rodyager/RWTS-PDFwriter/assets/1384461/c68af502-5f8a-46e8-b915-31d04e2af646">
But, if the size you want isn't there, you can scroll to the bottom of the pull down list and click on manage custom sizes ... and then hit the + sign to configure, name and add your desired size.
