### ISSUE TITLE
RWTS-PDFWriter.pkg can't be opened

### ISSUE THREAD

**Issue by pelargir** [rodyager/RWTS-PDFwriter#4]
The latest pkg version gives this security error when opened in Mac OS Catalina:

![Screen Shot 2020-06-18 at 11 41 34 AM](https://user-images.githubusercontent.com/3756/85042111-ce9f3480-b158-11ea-9d2a-93c4c5c26c34.png)

I'm not sure what needs to be done to prevent this from happening. Any ideas?

**Comment by tree-frog** [comment]
This has to do with your Gatekeeper security settings (System Preferences > Security & Privacy).  Instead of double-clicking the installer package, you can right-click it and select "Open" to launch it.

**Comment by pelargir** [comment]
Right, it's just inconvenient having to do that.

**Comment by rodyager** [comment]
I've resigned the package, and this time I have also had it notarized and and stapled. It will now install without Gatekeeper complaining.
Thanks for prompting me to work out how to persuade Apple to notarize this.

**Comment by pelargir** [comment]
That's incredible, thank you!
