### ISSUE TITLE
Cups Error when printing some files

### ISSUE THREAD

**Issue by gwena56** [rodyager/RWTS-PDFwriter#5]
The 0 Ko pdf is back !!! When i try to print some documents from a Windows App running on Wine 5.0 ... 
Thie error on cups

----

`E[23/Jun/2020:16:13:42 +0200] [Job 332] ERREURÂ : %%[ Error: undefinedresult; OffendingCommand: glyphshow; ErrorInfo: MetricsCount --nostringval-- ]%%.
E [23/Jun/2020:16:13:42 +0200] [Job 332] ERREURÂ : 
E [23/Jun/2020:16:13:42 +0200] [Job 332] ERREURÂ : %%[ Flushing: rest of job (to end-of-file) will be ignored ]%%
E [23/Jun/2020:16:13:42 +0200] [Job 332] ERREURÂ : %%[ Warning: PostScript error. No PDF file produced. ] %%
E [23/Jun/2020:16:13:42 +0200] [Job 332] Impossible de convertir le fichier PostScript.
E [23/Jun/2020:16:13:42 +0200] [Job 332] Job stopped due to filter errors; please consult the error_log file for details.
D [23/Jun/2020:16:13:42 +0200] [Job 332] The following messages were recorded from 16:13:42 to 16:13:42
D [23/Jun/2020:16:13:42 +0200] [Job 332] Adding start banner page "none".
D [23/Jun/2020:16:13:42 +0200] [Job 332] Queued on "PDFwriter" by "gwena".
D [23/Jun/2020:16:13:42 +0200] [Job 332] Auto-typing file...
D [23/Jun/2020:16:13:42 +0200] [Job 332] Request file type is application/postscript.
D [23/Jun/2020:16:13:42 +0200] [Job 332] File of type application/postscript queued by "gwena".
D [23/Jun/2020:16:13:42 +0200] [Job 332] Adding end banner page "none".
D [23/Jun/2020:16:13:42 +0200] [Job 332] time-at-processing=1592921622
D [23/Jun/2020:16:13:42 +0200] [Job 332] 4 filters for job:
D [23/Jun/2020:16:13:42 +0200] [Job 332] pstoappleps (application/postscript to application/vnd.apple-postscript, cost 10)
D [23/Jun/2020:16:13:42 +0200] [Job 332] pstopdffilter (application/vnd.apple-postscript to application/pdf, cost 200)
D [23/Jun/2020:16:13:42 +0200] [Job 332] cgpdftopdf (application/pdf to application/vnd.cups-pdf, cost 25)
D [23/Jun/2020:16:13:42 +0200] [Job 332] - (application/vnd.cups-pdf to printer/PDFwriter, cost 0)
D [23/Jun/2020:16:13:42 +0200] [Job 332] job-sheets=none,none
D [23/Jun/2020:16:13:42 +0200] [Job 332] argv[0]="PDFwriter"
D [23/Jun/2020:16:13:42 +0200] [Job 332] argv[1]="332"
D [23/Jun/2020:16:13:42 +0200] [Job 332] argv[2]="gwena"
D [23/Jun/2020:16:13:42 +0200] [Job 332] argv[3]="MKWS30 (Decision Explorer)"
D [23/Jun/2020:16:13:42 +0200] [Job 332] argv[4]="1"
D [23/Jun/2020:16:13:42 +0200] [Job 332] argv[5]="AP_D_InputSlot= finishings=3 media=A4 number-up=1 job-uuid=urn:uuid:8d1d2b25-a2b5-3451-6b8c-29d92beeaffe job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1592921622 time-at-processing=1592921622 document-name-supplied=00007.SPL PageSize=A4"
D [23/Jun/2020:16:13:42 +0200] [Job 332] argv[6]="/private/var/spool/cups/d00332-001"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[0]="<CFProcessPath>"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[1]="CUPS_CACHEDIR=/private/var/spool/cups/cache"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[2]="CUPS_DATADIR=/usr/share/cups"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[3]="CUPS_DOCROOT=/usr/share/doc/cups"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[4]="CUPS_FONTPATH=/usr/share/cups/fonts"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[5]="CUPS_REQUESTROOT=/private/var/spool/cups"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[6]="CUPS_SERVERBIN=/usr/libexec/cups"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[7]="CUPS_SERVERROOT=/private/etc/cups"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[8]="CUPS_STATEDIR=/private/etc/cups"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[9]="HOME=/private/var/spool/cups/tmp"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[10]="PATH=/usr/libexec/cups/filter:/usr/bin:/usr/sbin:/bin:/usr/bin"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[11]="SERVER_ADMIN=root@gwmbp-6.local"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[12]="SOFTWARE=CUPS/2.2.5"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[13]="TMPDIR=/private/var/spool/cups/tmp"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[14]="USER=root"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[15]="CUPS_MAX_MESSAGE=2047"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[16]="CUPS_SERVER=/private/var/run/cupsd"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[17]="CUPS_ENCRYPTION=IfRequested"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[18]="IPP_PORT=631"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[19]="CHARSET=utf-8"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[20]="LANG=fr_FR.UTF-8"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[21]="APPLE_LANGUAGE=fr-FR"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[22]="PPD=/private/etc/cups/ppd/PDFwriter.ppd"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[23]="RIP_MAX_CACHE=128m"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[24]="CONTENT_TYPE=application/postscript"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[25]="DEVICE_URI=pdfwriter:/"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[26]="PRINTER_INFO=PDFwriter"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[27]="PRINTER_LOCATION=PDFwriter"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[28]="PRINTER=PDFwriter"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[29]="PRINTER_STATE_REASONS=none"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[30]="CUPS_FILETYPE=document"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[31]="FINAL_CONTENT_TYPE=application/vnd.cups-pdf"
D [23/Jun/2020:16:13:42 +0200] [Job 332] envp[32]="AUTH_I****"
D [23/Jun/2020:16:13:42 +0200] [Job 332] Started filter /usr/libexec/cups/filter/pstoappleps (PID 71840)
D [23/Jun/2020:16:13:42 +0200] [Job 332] Started filter /usr/libexec/cups/filter/pstopdffilter (PID 71841)
D [23/Jun/2020:16:13:42 +0200] [Job 332] Started filter /usr/libexec/cups/filter/cgpdftopdf (PID 71842)
D [23/Jun/2020:16:13:42 +0200] [Job 332] Started backend /usr/libexec/cups/backend/pdfwriter (PID 71843)
D [23/Jun/2020:16:13:42 +0200] [Job 332] Message catalog filename is \"/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/Resources/French.lproj/cups_apple.strings\".
D [23/Jun/2020:16:13:42 +0200] [Job 332] Message catalog filename is \"/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/Resources/French.lproj/cups_apple.strings\".
D [23/Jun/2020:16:13:42 +0200] [Job 332] Message catalog filename is \"/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/Resources/French.lproj/cups_apple.strings\".
D [23/Jun/2020:16:13:42 +0200] [Job 332] cgpdftopdf - opened PPD file \"/private/etc/cups/ppd/PDFwriter.ppd\"...
D [23/Jun/2020:16:13:42 +0200] [Job 332] cgpdftopdf: PreferredRotation = 90
D [23/Jun/2020:16:13:42 +0200] [Job 332] cgpdftopdf - NO filtering is needed; passing data through.
D [23/Jun/2020:16:13:42 +0200] [Job 332] Writing PageSize code width = 595.000000, height = 842.000000
D [23/Jun/2020:16:13:42 +0200] [Job 332] PID 71840 (/usr/libexec/cups/filter/pstoappleps) exited with no errors.
D [23/Jun/2020:16:13:42 +0200] [Job 332] Set job-printer-state-message to "ERREURÂ : %%[ Error: undefinedresult; OffendingCommand: glyphshow; ErrorInfo: MetricsCount --nostringval-- ]%%.", current level=ERROR
D [23/Jun/2020:16:13:42 +0200] [Job 332] Stack:
D [23/Jun/2020:16:13:42 +0200] [Job 332] /hyphen
D [23/Jun/2020:16:13:42 +0200] [Job 332] .
D [23/Jun/2020:16:13:42 +0200] [Job 332] .
D [23/Jun/2020:16:13:42 +0200] [Job 332] .
D [23/Jun/2020:16:13:42 +0200] [Job 332] pstopdffilter/pstocupsraster failed with err number -31000
D [23/Jun/2020:16:13:42 +0200] [Job 332] PID 71841 (/usr/libexec/cups/filter/pstopdffilter) stopped with status 1.
D [23/Jun/2020:16:13:42 +0200] [Job 332] Hint: Try setting the LogLevel to "debug" to find out more.
D [23/Jun/2020:16:13:42 +0200] [Job 332] PID 71842 (/usr/libexec/cups/filter/cgpdftopdf) exited with no errors.
D [23/Jun/2020:16:13:42 +0200] [Job 332] PID 71843 (/usr/libexec/cups/backend/pdfwriter) exited with no errors.
D [23/Jun/2020:16:13:42 +0200] [Job 332] End of messages
D [23/Jun/2020:16:13:42 +0200] [Job 332] printer-state=3(idle)
D [23/Jun/2020:16:13:42 +0200] [Job 332] printer-state-message="Impossible de convertir le fichier PostScript."
D [23/Jun/2020:16:13:42 +0200] [Job 332] printer-state-reasons=none
`

**Comment by rodyager** [comment]
Will the same windows app print the same document to a macOS postscript printer? 

It looks as though the error is happening because the windows app is sending output that is not valid and produces a postscript error. The relevant part of your error output is:

`Error: undefinedresult; OffendingCommand: glyphshow; ErrorInfo: MetricsCount --nostringval-- `

Rod

**Comment by gwena56** [comment]
Not at all, no error with the mac os postscript printer ... it's happend with large pdf only ...
